# Generated by Django 5.0.7 on 2024-07-12 19:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="address_line",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="country",
            field=models.CharField(default="iran", max_length=255),
        ),
        migrations.AddField(
            model_name="address",
            name="create_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="address",
            name="last_update",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="address",
            name="province",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store_app.user",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="create_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="payment",
            name="last_update",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("U", "UPI"), ("CC", "Credit Card")],
                default="U",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="store_app.user",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="create_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="user",
            name="last_update",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
